[package]
name = "rusted_cypher"
version = "0.8.0"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "Send cypher queries to a neo4j database"
repository = "https://github.com/livioribeiro/rusted-cypher"
homepage = "https://github.com/livioribeiro/rusted-cypher"
documentation = "http://livioribeiro.github.io/rusted_cypher/rusted_cypher/"
readme = "README.md"
keywords = ["neo4j", "database", "query", "cypher", "graph"]
license = "MIT"
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "0.6", optional = true }
syntex = "0.26"

[dependencies]
hyper = "0.7"
url = "0.5"
serde = "0.6"
serde_json = "0.6"
serde_macros = { version = "0.6", optional = true }
rustc-serialize = { version = "0.3", optional = true }
semver = "0.2"
time = "0.1"
log = "0.3"
